---
#----------------------------------------------------------------------------------------------
# This is the report configuration file of the report builder app
# Please note: when changing values here, you need to check whether specific choice indexes
#             are used within R scripts
#----------------------------------------------------------------------------------------------

#----------------------------------------------------------
# IMPORTANT
# Please note that the following values are in the report config file of the report builder as well
# They have to be exactly the same
#----------------------------------------------------------
assumed_origin_choices:
  - "Somatic"
  - "Somatic (consider excluding germline)"
  - "Somatic (recommend excluding germline)"
  - "Donor cell derived"
  - "Uncertain"
  - "Germline"
vrf_na: "N/A"
flt3_Itd_Delete: "DELETE SECTION, NOT APPLICABLE"

#----------------------------------------------------------
# Report template variables
#----------------------------------------------------------
Patient: "PATIENT_IN"
Urn: "URN_IN"
Dob: "DOB_IN"
Sex: "SEX_IN"
Lab_No: "LAB_NO_IN"
Ext_Ref: "EXT_REF_IN"
Collected_Date: "COLLECTED_IN"
Received_Date: "RECEIVED_IN"
Specimen: "SPECIMEN_IN"
Requester: "REQUESTER_IN"
Referral_Lab: "REFERRAL_LAB_IN"
Clinical_Indication: "CLINICAL_INDICATION_IN"
Correlative_Morphology: "CORRELATIVE_MORPHOLOGY_IN"
Specimen_Details: "SPECIMEN_DETAILS_IN"
Results_Summary: "RESULTS_SUMMARY_IN"
Results_Summary1: "RESULTS_SUMMARY1_IN"
Results_Summary2: "RESULTS_SUMMARY2_IN"
Clinical_Interpretation1: "CLINICAL_INTERPRETATION1_IN"
Clinical_Interpretation2: "CLINICAL_INTERPRETATION2_IN"
Clinical_Interpretation3: "CLINICAL_INTERPRETATION3_IN"
Clinical_Interpretation4: "CLINICAL_INTERPRETATION4_IN"
Ddx41_variant_analysis: "DDX41_GERMLINE_VARIANT_ANALYSIS_IN"
Flt3_Itd: "FLT3_ITD_IN"
Reported_By1: "REPORTED_BY1_IN"
Reported_By2: "REPORTED_BY2_IN"
Authorised_By: "AUTHORISED_BY_IN"
Reported: "REPORTED_IN"
Coverage_table_text: "^Gene coverage in this sample is as follows"
Clinical_Context: "CLINICAL_CONTEXT_IN"
Panel_table_text: "^Panel Summary"
Variants_table_text: "^VRF . variant read frequency "
hgvsp_NA: "p.?"
